name: Build iOS Dylib

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Dylib
      run: |
        chmod +x build.sh
        ./build.sh
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: libprotected.dylib
        path: libprotected.dylib
